//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTicker.Web.StockServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceReference.StockWebServiceSoap")]
    public interface StockWebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockTicker.Web.StockServiceReference.GetListResponse GetList(StockTicker.Web.StockServiceReference.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.GetListResponse> GetListAsync(StockTicker.Web.StockServiceReference.GetListRequest request);
        
        // CODEGEN: Generating message contract since message UpdatePricesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockTicker.Web.StockServiceReference.UpdatePricesResponse UpdatePrices(StockTicker.Web.StockServiceReference.UpdatePricesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePrices", ReplyAction="*")]
        System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.UpdatePricesResponse> UpdatePricesAsync(StockTicker.Web.StockServiceReference.UpdatePricesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private string nameField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultModelOfArrayOfStockModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorField;
        
        private StockModel[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public StockModel[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockTicker.Web.StockServiceReference.UserCredentials UserCredentials;
        
        public GetListRequest() {
        }
        
        public GetListRequest(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            this.UserCredentials = UserCredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel GetListResult;
        
        public GetListResponse() {
        }
        
        public GetListResponse(StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrices", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePricesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StockTicker.Web.StockServiceReference.UserCredentials UserCredentials;
        
        public UpdatePricesRequest() {
        }
        
        public UpdatePricesRequest(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            this.UserCredentials = UserCredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePricesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel UpdatePricesResult;
        
        public UpdatePricesResponse() {
        }
        
        public UpdatePricesResponse(StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel UpdatePricesResult) {
            this.UpdatePricesResult = UpdatePricesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockWebServiceSoapChannel : StockTicker.Web.StockServiceReference.StockWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockWebServiceSoapClient : System.ServiceModel.ClientBase<StockTicker.Web.StockServiceReference.StockWebServiceSoap>, StockTicker.Web.StockServiceReference.StockWebServiceSoap {
        
        public StockWebServiceSoapClient() {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockTicker.Web.StockServiceReference.GetListResponse StockTicker.Web.StockServiceReference.StockWebServiceSoap.GetList(StockTicker.Web.StockServiceReference.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel GetList(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            StockTicker.Web.StockServiceReference.GetListRequest inValue = new StockTicker.Web.StockServiceReference.GetListRequest();
            inValue.UserCredentials = UserCredentials;
            StockTicker.Web.StockServiceReference.GetListResponse retVal = ((StockTicker.Web.StockServiceReference.StockWebServiceSoap)(this)).GetList(inValue);
            return retVal.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.GetListResponse> StockTicker.Web.StockServiceReference.StockWebServiceSoap.GetListAsync(StockTicker.Web.StockServiceReference.GetListRequest request) {
            return base.Channel.GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.GetListResponse> GetListAsync(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            StockTicker.Web.StockServiceReference.GetListRequest inValue = new StockTicker.Web.StockServiceReference.GetListRequest();
            inValue.UserCredentials = UserCredentials;
            return ((StockTicker.Web.StockServiceReference.StockWebServiceSoap)(this)).GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockTicker.Web.StockServiceReference.UpdatePricesResponse StockTicker.Web.StockServiceReference.StockWebServiceSoap.UpdatePrices(StockTicker.Web.StockServiceReference.UpdatePricesRequest request) {
            return base.Channel.UpdatePrices(request);
        }
        
        public StockTicker.Web.StockServiceReference.ResultModelOfArrayOfStockModel UpdatePrices(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            StockTicker.Web.StockServiceReference.UpdatePricesRequest inValue = new StockTicker.Web.StockServiceReference.UpdatePricesRequest();
            inValue.UserCredentials = UserCredentials;
            StockTicker.Web.StockServiceReference.UpdatePricesResponse retVal = ((StockTicker.Web.StockServiceReference.StockWebServiceSoap)(this)).UpdatePrices(inValue);
            return retVal.UpdatePricesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.UpdatePricesResponse> StockTicker.Web.StockServiceReference.StockWebServiceSoap.UpdatePricesAsync(StockTicker.Web.StockServiceReference.UpdatePricesRequest request) {
            return base.Channel.UpdatePricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockTicker.Web.StockServiceReference.UpdatePricesResponse> UpdatePricesAsync(StockTicker.Web.StockServiceReference.UserCredentials UserCredentials) {
            StockTicker.Web.StockServiceReference.UpdatePricesRequest inValue = new StockTicker.Web.StockServiceReference.UpdatePricesRequest();
            inValue.UserCredentials = UserCredentials;
            return ((StockTicker.Web.StockServiceReference.StockWebServiceSoap)(this)).UpdatePricesAsync(inValue);
        }
    }
}
